os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip

stages:
  - name: test1

jobs:
  include:
    - stage: test1
      name: testing
      script: true

after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
